### ISSUE TITLE
TAFFY — совместимость с iOS и Safari

### ISSUE THREAD

**Issue by oleg-aleynikov** [ifiction-ru/Az#1]
В Issues базы данных TAFFY есть информация о проблемах работы модуля с iOS и Safari:
https://github.com/typicaljoe/taffydb/issues/100
https://github.com/typicaljoe/taffydb/pull/101

Нужно разобраться, исправлено ли это.

**Comment by Nafanin** [comment]
Взял исправленный TAFFY здесь: https://github.com/mmikowski/taffydb
747e5cc9e193e67216c30d0d8af1355b61c54745
